<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MA415 Midterm Project - Isha Mukundan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="MA415_midterm_proj_files/libs/clipboard/clipboard.min.js"></script>
<script src="MA415_midterm_proj_files/libs/quarto-html/quarto.js"></script>
<script src="MA415_midterm_proj_files/libs/quarto-html/popper.min.js"></script>
<script src="MA415_midterm_proj_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MA415_midterm_proj_files/libs/quarto-html/anchor.min.js"></script>
<link href="MA415_midterm_proj_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MA415_midterm_proj_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MA415_midterm_proj_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MA415_midterm_proj_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MA415_midterm_proj_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="MA415_midterm_proj_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="MA415_midterm_proj_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MA415 Midterm Project - Isha Mukundan</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="usda-nass-strawberry-data-set" class="level2">
<h2 class="anchored" data-anchor-id="usda-nass-strawberry-data-set">USDA NASS Strawberry Data Set</h2>
<p>This document contains the process and results for data cleaning and exploratory data analysis (EDA) OF A USDA NASS Data Set regarding the production and sales of strawberries between the years of 2020 to 2023 in the states of California and Florida.</p>
<section id="read-in-data" class="level3">
<h3 class="anchored" data-anchor-id="read-in-data">Read in Data</h3>
<p>The raw USDA NASS Strawberry Data Set that is read in within the code is provided in the associated Github repository under the file name strawb_mar6.csv. An additional file under the name my_functions.R is also provided in the repository which provides function definitions for functions used within the rest of the code- particularly drop_one_value_col().</p>
</section>
<section id="clean-data" class="level3">
<h3 class="anchored" data-anchor-id="clean-data">Clean Data</h3>
<p>To provide an initial cleaning of the Strawberry Data Set the function drop_one_value_col() is utilized to remove any redundant columns or columns that are entirely NA- which in both cases are columns that only have one value.</p>
<p>When looking at the cleaned Strawberry Data Set it can be seen that the data set can be further split into two more broad programs of <code>CENSUS</code> and <code>SURVEY</code> as the information (variables of interest) held within both programs vastly differ. For example, the <code>CENSUS</code> data holds information regarding Gains, Losses, and Net Income while the <code>SURVEY</code> data provides insight into utilized chemicals. To therefore ease the process of further data cleaning the cleaned Strawberry Data Set will be split into two new data sets: one consisting of <code>CENSUS</code> data and one consisting of <code>SURVEY</code> data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Looking for single value columns in data frame:  straw_cen"
[1] "Columns dropped:"
    Program      Period Week Ending 
   "CENSUS"      "YEAR"          NA </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Looking for single value columns in data frame:  straw_sur"
[1] "Columns dropped:"
       Program      Commodity         CV (%) 
      "SURVEY" "STRAWBERRIES"             NA </code></pre>
</div>
</div>
<section id="clean-survey-data" class="level4">
<h4 class="anchored" data-anchor-id="clean-survey-data">Clean Survey Data</h4>
<p>As eventually I wanted to gain insight into the usage of chemicals in the production of strawberries, I further cleaned the <code>SURVEY</code> Data as the information within this <code>Program</code> provided the data regarding the type and usage of chemicals in the growing process. The original <code>SURVEY</code> Data consists of columns that have multiple data entries in each as well as columns that hold data that should be placed in a different column.</p>
<p>The <code>grepl()</code> function is utilized within the code to recognize patterns within columns of data to shift the location of incorrectly placed data to the correct ones. To tackle the issue regarding multiple data entries in a single cell the <code>separate_wider_delim()</code> function is used to split the multiple entries into separate columns based on a chosen delimiter.</p>
<p>First, the non chemical columns in the <code>SURVEY</code> data will be cleaned.</p>
<p>Next, the chemical related columns of the <code>SURVEY</code> data is cleaned in a similar manner- using separate_wider_delim() to separate columns with multiple values and select() and gsub() to respectively remove unwanted columns and remove unwanted parentheses.</p>
<p>The cleaned Strawberry <code>SURVEY</code> data is saved as a .csv for further analysis purposes. This file is found within the Github repository under the name survey_clean.csv</p>
<p>Since further analysis will consider and compare the state of California and Florida I split the cleaned <code>SURVEY</code> data into two further data sets: one where the state of interest is California and one where it is Florida.</p>
</section>
<section id="clean-census-data" class="level4">
<h4 class="anchored" data-anchor-id="clean-census-data">Clean Census Data</h4>
<p>As I wanted to also gain insight into the connection between of sales, production, and net income for strawberries production within the two states, I further cleaned the <code>CENSUS</code> Data as the information within this <code>Program</code> provided the economic data needed to gain clarity on these topics. Like the <code>SURVEY</code> data, the original <code>CENSUS</code> Data also consists of columns that have multiple data entries as well as columns that hold data that should be placed in a different column.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "INCOME, NET CASH FARM" "STRAWBERRIES"         </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Looking for single value columns in data frame:  s_cen_ca_fl_inc"
[1] "Columns dropped:"
                   Year               Commodity                   Fruit 
                 "2022" "INCOME, NET CASH FARM"                "INCOME" 
               Category                  Metric 
       " NET CASH FARM"        " MEASURED IN $" </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Looking for single value columns in data frame:  s_cen_ca_fl_str"
[1] "Columns dropped:"
                                  Year                              Commodity 
                                "2021"                         "STRAWBERRIES" 
                                 Fruit                                 Domain 
                        "STRAWBERRIES"                       "ORGANIC STATUS" 
                       Domain Category 
"ORGANIC STATUS: (NOP USDA CERTIFIED)" </code></pre>
</div>
</div>
<p>Now looking just at the data set where the <code>Commodity</code> of interest is <code>INCOME</code>, the same process undertaken to clean the <code>SURVEY</code> data is repeated here for the <code>CENSUS</code> data through the use of the functions separate_wider_delim(), select(), and gsub(). Here separate_wider_delim() is used to separate and get rid of the leading “OF OPERATIONS -” and “OF PRODUCERS -” with “F” and then “-” as delimiters.</p>
<p>The values in <code>FARM SALES</code> are provided as ranges between two values and to make data visualization easier I split the Range column into its <code>Lower</code> and <code>Upper</code> bounds. These ranges however had additional information indicating the units of interest ($ or ACRES) and so gsub() was used so that only numerical values were left. There were additionally two special cases where OR MORE and LESS THAN were used, so to ensure only numerical values were left I changed LESS THAN (Value) to go from 0 to the particular value by using gsub() to substitute out LESS THAN for “0-” and used separate_wider_delim to keep 0 in the <code>Lower</code> column and (Value) in the Upper bound column. A similar process was utilized for OR MORE but rather than 0 the <code>Upper</code> bound for that row was left as NA, as the cap for the Farm Sales value is unknown.</p>
<p>The cleaned Strawberry <code>CENSUS</code> data where <code>Commodity</code> is <code>INCOME</code> is saved as a .csv for further analysis purposes. This file is found within the Github repository under the name census_inc_clean.csv</p>
<p>Since further analysis will consider and compare the state of California and Florida I split the cleaned <code>CENSUS</code> data, where the <code>Commodity</code> is <code>INCOME</code> into two further data sets: one where the state of interest is California and one where it is Florida. Within each data set however, there is additionally a separation between <code>OPERATIONS</code> and <code>PRODUCERS</code> so each State specific data set will be further split into two new data sets so that there is an individual <code>OPERATIONS</code> and <code>PRODUCERS</code> for both states.</p>
<p>Now looking at the data set where the <code>Commodity</code> of interest is <code>STRAWBERRIES</code>, the same process undertaken to clean the earlier <code>CENSUS</code> data is repeated here the use of the functions grepl() and select(). Here grepl() is used to move all the entries in the <code>Item</code> column that begin with “MEASURED” to the <code>Metric</code> column and all entries with “ORGANIC -” to the <code>Item</code> column from ’<code>Category</code>. This second shift leaves everything in Category to have only one value so it can be dropped from the cleaned final data.</p>
<p>The cleaned Strawberry <code>CENSUS</code> data where <code>Commodity</code> is <code>STRAWBERRIES</code> is saved as a .csv for further analysis purposes. This file is found within the Github repository under the name census_str_clean.csv</p>
<p>Since further analysis will consider and compare the state of California and Florida I split the cleaned <code>CENSUS</code> data, where the <code>Commodity</code> is <code>STRAWBERRIES</code> into two further data sets: one where the state of interest is California and one where it is Florida.</p>
</section>
</section>
<section id="data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis">Data Analysis</h3>
<p>Following the completion of the Data Cleaning portion of the project, I now focus on performing exploratory data analysis to uncover patterns and gain insights into potential trends and explanations that underlie the current production, growth, and sales system of strawberries. By looking into the use of chemicals in the growth of strawberries, insights can be gained regarding the impact of various chemicals on yield, quality, and overall productivity. This can help identify which chemicals are most effective and sustainable in strawberry cultivation, as well as how environmental or regulatory factors might be influencing their usage.</p>
<p>Furthermore, examining how farm sales affect net income provides valuable context for understanding the financial health of strawberry producers. By identifying the farm sales ranges where producers begin to experience positive net income, we can uncover the thresholds at which farm operations become profitable. This information is vital for growers and stakeholders in planning and optimizing production and sales strategies.</p>
<p>Additionally, understanding how much sales are made based on market type—whether organic, fresh, or processing— can reveal significant insights into market preferences, demand, and pricing dynamics. This information can help to guide producers to tailor their marketing and operational efforts more effectively. Analyzing this data can help to identify which market types are more lucrative and explore the potential for growth in emerging markets such as organic strawberries.</p>
<section id="data-analysis---chemicals" class="level4">
<h4 class="anchored" data-anchor-id="data-analysis---chemicals">Data Analysis - Chemicals</h4>
<p>An important area of focus in this analysis is the use of chemicals in strawberry cultivation. Chemicals such as pesticides, herbicides, and fungicides are commonly used to enhance yields and protect crops from pests and diseases. However, concerns about the environmental impact and potential health risks associated with these chemicals have sparked ongoing debates. By examining the trends in chemical usage, particularly in major strawberry-producing states like California and Florida, this section aims to understand the patterns and implications of chemical applications in strawberry farming. This insight is crucial for identifying sustainable practices that balance productivity with environmental and consumer health considerations.</p>
<p>This data set provides insights into the four main classes of chemicals used (fungicides, herbicide, insecticide, other) as well as fertilizers and so I was interested in the particular breakdown of which class of chemicals was most used in each state and whether the main class of chemical used between the two differed. To visualize this comparison I created a 2 variable bar graph, using ggplot, to show the difference in counts of chemical and fertilizer uses for the four major classes of chemicals between California and Florida.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Domain'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'Domain'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MA415_midterm_proj_files/figure-html/create%20plot%20to%20investigate%20chemical%20class%20use-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the produced bar graph, it can be seen how California seems to have a higher reliance on chemicals compared to Florida, as for all chemical types other than herbicides California has a higher count. While fungicides are the most commonly used chemical in Florida, California’s most commonly used chemical type is insecticides but it too often uses fungicides- even more than Florida. This discrepancy in the usage amount and type of chemical class used can be due to the fact that California may face greater pest and disease pressures, whereas Florida may focus on different environmental or farming practices that are less reliant on chemicals even when faced with such pressures. These differences in chemical usage could have important implications for sustainability and environmental impact, highlighting the need for tailored strategies in each state to optimize agricultural practices and manage pests and diseases effectively.</p>
<p>Now that more broad insight into the differences between the classes of chemicals between the two states have been found, I am interested in seeing if there are any specific chemicals that are commonly used in both California and Florida and how their usage amounts differ between each other as well as over the years. To help satisfy this curiosity I created a table to visualize the top 10 chemicals used in each state respectively based in the amount used measured in pounds. By filtering each data set based on the values measured in pounds and summing up this measurement for each chemical name, a running total of the total usage of a particular chemical could be found.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion
Warning: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output-display">
<table class="lightable-classic caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Top 10 Most Used Chemicals in California and Florida</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
California
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Florida
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total Usage (LB)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total Usage (LB)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CHLOROPICRIN</td>
<td style="text-align: right;">16991600</td>
<td style="text-align: left;">CAPTAN</td>
<td style="text-align: right;">279100</td>
</tr>
<tr class="even">
<td style="text-align: left;">DICHLOROPROPENE</td>
<td style="text-align: right;">2491200</td>
<td style="text-align: left;">THIRAM</td>
<td style="text-align: right;">254500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SULFUR</td>
<td style="text-align: right;">1849300</td>
<td style="text-align: left;">CYPRODINIL</td>
<td style="text-align: right;">15200</td>
</tr>
<tr class="even">
<td style="text-align: left;">METAM-POTASSIUM</td>
<td style="text-align: right;">1040400</td>
<td style="text-align: left;">FLUDIOXONIL</td>
<td style="text-align: right;">10600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CAPTAN</td>
<td style="text-align: right;">856700</td>
<td style="text-align: left;">NOVALURON</td>
<td style="text-align: right;">2600</td>
</tr>
<tr class="even">
<td style="text-align: left;">THIRAM</td>
<td style="text-align: right;">365800</td>
<td style="text-align: left;">SPINETORAM</td>
<td style="text-align: right;">700</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PENDIMETHALIN</td>
<td style="text-align: right;">82200</td>
<td style="text-align: left;">ACETAMIPRID</td>
<td style="text-align: right;">500</td>
</tr>
<tr class="even">
<td style="text-align: left;">MALATHION</td>
<td style="text-align: right;">48500</td>
<td style="text-align: left;">CHLORANTRANILIPROLE</td>
<td style="text-align: right;">400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIFENAZATE</td>
<td style="text-align: right;">45400</td>
<td style="text-align: left;">THIAMETHOXAM</td>
<td style="text-align: right;">400</td>
</tr>
<tr class="even">
<td style="text-align: left;">CYPRODINIL</td>
<td style="text-align: right;">41600</td>
<td style="text-align: left;">ABAMECTIN</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Based on the table above it can be seen that the three most used chemicals common to both California and Florida (based on their total usage in pounds) are Captan, Thiram, and Cyprodinil- all of which fall under the fungicide class of chemicals. According to PubMed both Captan and Thiram as chemicals exhibit moderate acute toxicity if encountered via oral or inhalation exposure (Cat II and III), while Cyprodinil poses relatively little toxicity risk (Cat III &amp; I4). The fact that these chemicals which are some of the most commonly used in both states do to some extent post toxicity risk mY lead consumers to be more wary about purchasing such products if they are more aware about it in the future. These three chemicals were the top three most used in Florida which follows what was seen in the bar graph above where of the classes of chemicals Florida had the most number of fungicides. The largest use of the fungicides in Florida may imply that in this state Fungi are the largest threat the strawberry growing compared to insects or herbs. The top two chemicals used in California are under the the other class of chemicals, which I found interesting as with the high number of fungicides and insecticides seen in the bar graph to be used in California I was expecting their to be both classes in the top 5 most used chemicals.</p>
<p>After finding the three chemicals that were most commonly used in both states, I was interested in uncovering by how much that total usage of each of these chemicals changed over the years for California and Florida. To visualize this, I create a line plot, using ggplot, that plotted the total usage trajectory of each of the three top chemicals over the years 2021 and 2023 for the two states.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MA415_midterm_proj_files/figure-html/create%20a%20plot%20to%20visualize%20how%20the%20top%203%20shared%20chemical%20usage%20changed%20over%20time%20in%20both%20states-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the two line graphs produced above, it can be seen that for both California and Florida the usage of Captan and Cyprodinil have slowly increased over the years while the action of the chemical Thiram changes between the states. In California, the yearly usage of the chemical Thiram also goes up (similar to the other two chemicals), but in Florida the yearly usage of the same chemical drops instead. In California, the upward trend in Thiram usage could be driven by rising pest challenges or changing environmental factors that make this specific chemical more necessary. In contrast, the declining use of Thiram in Florida may suggest a shift in pest management strategies, possibly due to changes in pest pressure or the adoption of alternative chemicals to counter the particular fungi that this chemical in particular addresses. This might be the case rather than a more overarching shift away from fungicides as the other two fungicides (Captan and Cyprodinil) are still being utilized as the years progress.</p>
</section>
<section id="data-analysis---income" class="level4">
<h4 class="anchored" data-anchor-id="data-analysis---income">Data Analysis - Income</h4>
<p>An additionally important area of focus in this analysis is the economic trends that follow strawberry production within the two states. Understanding how different levels of sales contribute to profitability is crucial for evaluating the financial sustainability of such farms. Identifying the sale thresholds at which farms begin to experience positive net income, can help uncover key insights that can optimize production and sales strategies. Additionally, examining income in relation to market types—whether organic, fresh, or processing—can provide valuable context for understanding market preferences. This helps identify which market types are more lucrative, allowing producers to better target their efforts and capitalize on high-demand areas.</p>
<p>The data provided within the <code>CENSUS</code> portion of the data set provides insight into the correlation between Farm Sales and Net Income and I was interested in seeing the relationship between the two variables, particularly in regards to at which range of farm sales does the farm being to produce a positive net income. To visualize this I created a table that shows the net income of each state for a give range of Farm Sales in dollars.</p>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-classic caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>California and Florida Average Net Income in 2022 by Farm Sales</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Farm Sales ($)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
California
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Florida
</div></th>
</tr>
<tr class="odd">
<th style="text-align: right;" data-quarto-table-cell-role="th">Lower</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Upper</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">CV (%)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">CV (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">999</td>
<td style="text-align: left;">-$420.67M</td>
<td style="text-align: left;">-10.7</td>
<td style="text-align: left;">-$224.16M</td>
<td style="text-align: left;">-23.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">1000</td>
<td style="text-align: right;">2499</td>
<td style="text-align: left;">-$61.26M</td>
<td style="text-align: left;">-36.6</td>
<td style="text-align: left;">-$50.45M</td>
<td style="text-align: left;">-12.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2500</td>
<td style="text-align: right;">4999</td>
<td style="text-align: left;">-$81.06M</td>
<td style="text-align: left;">-22.6</td>
<td style="text-align: left;">-$47.60M</td>
<td style="text-align: left;">-14.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">5000</td>
<td style="text-align: right;">9999</td>
<td style="text-align: left;">-$92.08M</td>
<td style="text-align: left;">-16.0</td>
<td style="text-align: left;">-$44.90M</td>
<td style="text-align: left;">-25.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10000</td>
<td style="text-align: right;">24999</td>
<td style="text-align: left;">-$101.38M</td>
<td style="text-align: left;">-29.6</td>
<td style="text-align: left;">-$48.35M</td>
<td style="text-align: left;">-29.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">25000</td>
<td style="text-align: right;">49999</td>
<td style="text-align: left;">-$113.21M</td>
<td style="text-align: left;">-25.0</td>
<td style="text-align: left;">-$21.08M</td>
<td style="text-align: left;">-64.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50000</td>
<td style="text-align: right;">99999</td>
<td style="text-align: left;">-$31.06M</td>
<td style="text-align: left;">(H)</td>
<td style="text-align: left;">$16.92M</td>
<td style="text-align: left;">83.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">100000</td>
<td style="text-align: right;">249999</td>
<td style="text-align: left;">-$57.68M</td>
<td style="text-align: left;">-88.6</td>
<td style="text-align: left;">$26.36M</td>
<td style="text-align: left;">84.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">250000</td>
<td style="text-align: right;">499999</td>
<td style="text-align: left;">$203.68M</td>
<td style="text-align: left;">70.5</td>
<td style="text-align: left;">$104.15M</td>
<td style="text-align: left;">25.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">500000</td>
<td style="text-align: right;">999999</td>
<td style="text-align: left;">$209.18M</td>
<td style="text-align: left;">88.7</td>
<td style="text-align: left;">$108.72M</td>
<td style="text-align: left;">34.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">$12,219.73M</td>
<td style="text-align: left;">6.4</td>
<td style="text-align: left;">$2,412.57M</td>
<td style="text-align: left;">5.9</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Looking at the table above it can be seen how Florida begins to make a profitable (net positive) income at an earlier Farm Sale range when compared to California. For Florida, a positive net income starts as Farm Sales are between $50,000 and $99,999 while California only starts seeing a positive net income when Farm Sales are significantly higher between $250,000 and $499,999. This disparity suggests that Florida farmers can reach profitability at smaller scales, likely due to factors such as lower operational costs or reduced land and labor expenses. Its agricultural industry may also face less competition, allowing producers to become profitable more easily. On the other hand, California’s higher costs, driven by factors like labor, land, environmental regulations, and a larger, more competitive agricultural industry, demand higher sales to offset these expenses and reach profitability. Additionally, California’s farmers may deal with larger production volumes or more complex farming practices that contribute to higher operational costs. This difference in profitability thresholds also highlights the impact of scale economies in California, where larger-scale operations are needed to cover costs and achieve profit.</p>
<p>In addition to looking at the affect of Farm Sales on Net Income I was also interested in looking to see how sales in general were affected based on the market type used- whether it is organic, fresh market, or processing. However, the data in the given data set is very limited and missing some values, so the full scope of my question could not be considered but parts of it are able to. California has information for all three market types (organic, fresh market, and processing) when sales are <code>MEASURED BY CWT</code>, so I am interested to compare and see which market type produces the most sales for strawberries grown in California. I visualized this comparison through the generation of a bar graph, using ggplot, the compares the sale methods by weight.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MA415_midterm_proj_files/figure-html/create%20figure%20to%20compare%20organic,%20fresh%20market,%20and%20processing%20sales%20in%20california-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar graph highlights that in California, the vast majority of strawberry sales come from the fresh market and organic sectors rather than processing, suggesting a strong consumer preference for fresh and organic produce. The larger pull by the fresh and organic markets to consumers may be to a perception that fresher produce is better quality and more beneficial to those who eat it as well as the environment. This means that it would be import for California farmers to prioritize these markets, as they offer higher profitability (sales) compared to processed strawberries, that could come in the form of jams or jellies, meaning that more land, space, and workforce could be allocated for these sectors.</p>
<p>In the given data set however, Florida has no processing data and California only has hidden values for the Fresh Market and Processing sales in $, so instead I will compare organic and fresh market sales measured by weight/volume (in CWT) between the two states. To make this comparison I will generate a 2 variable bar graph, using ggplot, that compares the Value of product sold, in weight, for each market type between the two states.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MA415_midterm_proj_files/figure-html/create%20figure%20to%20compare%20organic%20+%20fresh%20market%20sales%20between%20california%20and%20florida-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the above bar graph it can be seen that for a given state the weight of produce sold is either exactly the same or very similar regardless of whether the sale type was in Fresh Market or Organic. However, comparing the two states together, it can be seen that by volume in both sale types California sells a significant amount more of strawberries, around 21 times more, than Florida. This stark contrast points to California’s larger agricultural scale, more extensive production capacity, and perhaps greater market reach allowing the state to sell much more of its goods. California’s dominance in strawberry sales likely reflects its established infrastructure, larger growing areas, and longer growing seasons, while Florida, though a significant producer (the second largest of all the states) seems to operate on a comparatively smaller scale.</p>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>In conclusion, the data cleaning and exploratory data analysis (EDA) processes have provided valuable insights into the complexities of strawberry production, sales, and chemical usage across California and Florida. These preliminary analyses have allowed for the identification of key patterns, such as the differing profitability thresholds between the two states and the significant difference in the volume of strawberries sold. However, this is just the beginning as the analysis I provided so far in this document has only scratched the surface of all the information and comparisons that could be generated through the original data set- meaning that are many more areas that need further exploration. Further analysis into this data set as well as creating others through USDA that may focus even more heavily on, for example, the economic situation of strawberry production, could help optimize farming strategies and contribute further to more sustainable practices. Continuing analysis through this cleaned data set can help uncover more valuable insights for strawberry producers and stakeholders in the agricultural industry.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>